version: "3"
services:
  mysql:
    image: mariadb
    volumes:
      - ./db/sql:/docker-entrypoint-initdb.d
      - ./data:/var/lib/mysql
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_HOST}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
