version: '3'

services:
  seigo2016-lms:
    build: .
    image: seigo2016-lms-app
    container_name: seigo2016-lms
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    environment:
      - TZ=Asia/Tokyo
      - SECRET_KEY=${SECRET_KEY}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    restart: always
    tty: true
    networks:
      - db_default

networks:
    db_default:
      external: true