version: '3'

services:
  app:
    build: .
    image: seigo2016-lms-app
    environment:
      - TZ=Asia/Tokyo
      - SECRET_KEY=${SECRET_KEY}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    restart: always

